### ISSUE TITLE
Flushing after invocation

### ISSUE THREAD

**Issue by osteenbergen** [spriteCloud/teelogger#3]
## Problem

Sometimes error messages are not visible in the console output of a program, which complicated debugging. Adding `STDOUT.flush` or `puts` statements flushes the IO making the log visible. This only flushes the STDOUT and not any file IO
## Solution

Provide an option to flush a logger after N invocations. Different loggers should be able to use different values for N

**Comment by ghost** [comment]
This is actually an interesting thing in the Ruby logger. Essentially, the logger deals with IO objects, and a) either logs to a given IO object like STDOUT, or b) create an IO object for a given filename.

If it creates an IO object, it sets the object's sync flag - meaning all writes _should_ be immediately flushed. This then only applies to file logs, not to STDOUT logs, of course.

[ Curiously you can see some kind of bug history there: there's a function that either creates a file or opens a file. If the file is created, the sync flag is set - but not if it's opened (already exists). But on the return value of the function, the sync flag is set anyway. ]

The upshot is that:
a) we can set the sync flag on all IO objects passed to teelogger, but then give the user less control, or
b) in user code, user sets e.g. STDOUT.sync = true before passing it to teelogger, or
c) we also take care of opening files in teelogger, just in case the weirdness in the ruby logger's code means we can't rely on them setting the sync flag well.

Now...

Since the logger already syncs file IO, it follows that that isn't reliable. It would suggest that we need to take care of creating IO objects ourselves, in which case flushing them is also not a problem.

**Comment by ghost** [comment]
Hmm.. further reading, IO.sync and IO.flush don't actually solve the issue; they relate to Ruby's own buffering.
