### ISSUE TITLE
Example does not work?

### ISSUE THREAD

**Issue by BurdetteLamar** [spriteCloud/teelogger#9]
I've had trouble with teelogger.  Eventually tried just to run the simplest example from the doc.  Got what's below.

Does this no longer work?

Thanks,
Burdette

$ gem list teelogger

*** LOCAL GEMS ***

teelogger (0.5.1)

$ cat t.rb
require 'teelogger'

log = TeeLogger::TeeLogger.new(STDOUT, "filename.log")
log.level = Logger::WARN # applies to all outputs
log.level = "INFO"       # convenience shortcut

$ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]

$ ruby t.rb
Logging to STDOUT initialized with level INFO.
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogger/extensions.
rb:24:in `fsync': Bad file descriptor @ rb_io_fsync - <STDOUT> (Errno::EBADF)
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogge
r/extensions.rb:24:in `flush'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogge
r.rb:105:in `add_logger'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogge
r.rb:133:in `block in initialize'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogge
r.rb:132:in `each'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/teelogger-0.5.1/lib/teelogge
r.rb:132:in `initialize'
        from t.rb:3:in `new'
        from t.rb:3:in `<main>'

**Comment by osteenbergen** [comment]
Hi Burdette,

Haven't used the code in a while, but if i run the example it seems to be working as expected.

I see you run Ruby on Windows and an older version so that is a bit different than my current setup.

Can you test the following code for me:
```
io = File.new('testfile.txt', File::WRONLY | File::APPEND | File::CREAT)
io.write 'An example'
io.flush
```

Its a short test of the code that seems to be causing this issue.

I suspect that the issue is due to your old ruby installation. Ruby has had issues with fsync on windows and some of those should be patched (https://bugs.ruby-lang.org/issues/9153)

My recommendation is upgrading or reinstalling Ruby. SpriteCloud has a small blog article on how to install Ruby on Windows: https://spritecloud.com/2015/04/complete-setup-guide-for-ruby-cucumber-and-watir-on-windows/ Just follow the article until you reach the Cucumber setup in step 4. Be sure to pick the latest version of Ruby that your project supports (2.2.6 for example, or the latest 2.3.3)

Good luck and if this solved your issue please let me know

**Comment by BurdetteLamar** [comment]
Thanks much, Onno!

Here's the snippet, executed in irb:

$ irb
irb(main):001:0> io = File.new('testfile.txt', File::WRONLY | File::APPEND | <new('testfile.txt', File::WRONLY | File::APPEND | File::CREAT)
=> #<File:testfile.txt>
irb(main):002:0> io.write 'An example'
=> 10
irb(main):003:0> io.flush
=> #<File:testfile.txt>

I'll look into upgrading my Ruby installation.

**Comment by osteenbergen** [comment]
Ok so the code example doesn't trigger it directly. That would have made it easier.

Please do upgrade your installation and try again. If it continues to throw errors I will try to replicate your setup.

**Comment by BurdetteLamar** [comment]
Upgrade solved it!

$ ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

Thanks for all help!
